alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: hello-website
    match:
      path:
        prefix: /
name: hello-website
region: tor
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: jmulhern/hello-website
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: hello-website
  run_command: npm start
  build_command: npm install --legacy-peer-deps
  source_dir: /
